name: Build and Push with Docker

on:
  push:
    branches:
      - main

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Google Cloud authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

      - name: Authenticate Docker to Artifact Registry
        run: |
            echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > key.json
            cat key.json | docker login -u _json_key --password-stdin https://asia-south1-docker.pkg.dev

      - name: Build and push eshoppublicapi
        run: |
          docker build -t asia-south1-docker.pkg.dev/asif-345/siri-test-repo/eshoppublicapi:latest -f src/PublicApi/Dockerfile .
          docker push asia-south1-docker.pkg.dev/asif-345/siri-test-repo/eshoppublicapi:latest

      - name: Build and push eshoponwebmvc
        run: |
          docker build -t asia-south1-docker.pkg.dev/asif-345/siri-test-repo/eshoponwebmvc:latest -f src/Web/Dockerfile .
          docker push asia-south1-docker.pkg.dev/asif-345/siri-test-repo/eshoponwebmvc:latest