name: Build and Push with Skaffold

on:
  push:
    branches:
      - main

jobs:
  skaffold-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Google Cloud authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
        
    #   - name: Build and push eshoponwebmvc
    #     run: |
    #       docker build -t asia-south1-docker.pkg.dev/asif-345/siri-test-repo/eshoponwebmvc:latest -f src/Web/Dockerfile .
    #       docker push asia-south1-docker.pkg.dev/asif-345/siri-test-repo/eshoponwebmvc:latest

      - name: Build and push eshoppublicapi
        run: |
          docker build -t asia-south1-docker.pkg.dev/asif-345/siri-test-repo/eshoppublicapi:latest -f src/PublicApi/Dockerfile .
          docker push asia-south1-docker.pkg.dev/asif-345/siri-test-repo/eshoppublicapi:latest